title: Sabir Jan - AI/ML & Interactive Arts Portfolio
email: saber8ronaldo@gmail.com
github_username: Saber7Jan

description: Showcasing AI projects, research, and creative achievements in technology and arts.

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md
  - projects.md
  - education.md
  - awards.md
  - cv.md
  - contact.md

baseurl: ""                     # Important - empty for root domain
url: "https://saber7jan.github.io/Sabir-Jan-portfolio"   # Optional but good for absolute links
permalink: /:title/
